[build]
  base = "client"
  command = "npm run build"
  publish = "build"

# Uncomment and set if you use Netlify Functions
# [build]
#   functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200